name: Push updates to examples
on:
 workflow_dispatch:
 push:
jobs:
  updateexamples:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        examples:
          - name: example1
            key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: example2
            key: ${{ secrets.SSH_PRIVATE_KEY_EXAMPLE2 }}

    steps:
      - uses: actions/checkout@v3
      - name: Pull latest version
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${{  matrix.examples.key }}"
          # diagnostics
          ssh-add -L
          echo Cloning ssh://git@github.com/diarmidmackenzie/sample-${{ matrix.examples.name }}.git
          git clone ssh://git@github.com/diarmidmackenzie/sample-${{ matrix.examples.name }}.git
          echo Copy latest code into repo.
          cp -R examples/${{ matrix.examples.name }}/* sample-${{ matrix.examples.name }}

      - name: Push to Git
        run: |
          cd sample-${{ matrix.examples.name }}
          eval `ssh-agent -s`
          ssh-add - <<< "${{  matrix.examples.key }}"
          # diagnostics
          ssh-add -L
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo git add .
          git add .
          # Only commit if there is something changed that needs committing.
          echo git diff-index
          git diff-index HEAD || git commit -m "Updated from latest code"
          echo git push
          git push

