name: Push updates to examples
on:
 workflow_dispatch:
 push:
jobs:
  updateexamples:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        example-name: ["example1", "example2"]

    steps:
      - uses: actions/checkout@v3
      - name: Pull latest version
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY_EXAMPLE2 }}"
          # diagnostics
          ssh-add -L
          echo Cloning ssh://git@github.com/diarmidmackenzie/sample-${{ matrix.example-name }}.git
          git clone ssh://git@github.com/diarmidmackenzie/sample-${{ matrix.example-name }}.git
          echo Copy latest code into repo.
          cp -R examples/${{ matrix.example-name }}/* sample-${{ matrix.example-name }}

      - name: Push to Git
        run: |
          cd sample-${{ matrix.example-name }}
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY_EXAMPLE2 }}"
          # diagnostics
          ssh-add -L
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo git add .
          git add .
          # Only commit if there is something changed that needs committing.
          echo git diff-index
          git diff-index HEAD || git commit "Updated from latest code"
          echo git push
          git push

