name: Push updates
on: workflow_dispatch
jobs:
  updateexamples:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        example-name: ["example1", "example2"]

    steps:
      - uses: actions/checkout@v3
      - name: Pull latest version
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          # diagnostics
          ssh-add -L
          git clone ssh://git@github.com/diarmidmackenzie/sample-${{ matrix.example-name }}.git
          cp -R examples/${{ matrix.example-name }}/* sample-${{ matrix.example-name }}

      - name: Push to Git
        run: |
          cd sample-${{ matrix.example-name }}
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          # diagnostics
          ssh-add -L
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated from latest code"
          git push

