name: Fetch updates to latest code from master repo
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull latest version
        run: |
          git clone https://github.com/diarmidmackenzie/sample-example
          cp -R examples/example1/* sample-example
          pwd
          cd sample-example
          pwd

      - name: Push to Git
        run: |
          pwd
          cd sample-example
          pwd
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated from latest code"
          git push

