name: Push updates
on: workflow_dispatch
jobs:
  updateexamples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull latest version & push to git.
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          # diagnostics
          ssh-add -L
          git clone ssh://git@github.com/diarmidmackenzie/sample-example.git
          cp -R examples/example1/* sample-example
          cd sample-example
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated from latest code"
          git push

