name: Push updates to examples
on: push
jobs:
  updateexamples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull latest version
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          # diagnostics
          ssh-add -L
          git clone ssh://git@github.com/diarmidmackenzie/sample-example.git
          cp -R examples/example1/* sample-example

      - name: Push to Git
        run: |
          cd sample-example
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          # diagnostics
          ssh-add -L
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          # Only commit if there is something changed that needs committing.
          git diff-index --quiet HEAD || git commit "Updated from latest code"
          git push

